### ISSUE TITLE
Update docs to reflect multi task use

### ISSUE THREAD

**Issue by sbialobok** [drGrove/grunt-docker-io#2]
I was running into issues using the plug-in when following the README as it currently reads.  If you setup your grunt config with only options

```
docker_io: {
    options: {
        ...
    }
}
```

Grunt will annoying silently fail that task with no feedback as to what happened.  What DID happen however is the isValidMultiTaskTarget check failed when running multi task.  I guess if you setup a multi-task you need more than just the "options" inside your config declaration.

You'll need to wrap the options in a target or just put an empty target below your options (i think)

```
docker_io: {
    local: {
        options: {
            ...
        }
    }
}

OR

docker_io: {
    options: {
        ...
    },
    local: {
    }
}
```

**Comment by drGrove** [comment]
PR: #3
